version: 0.0  # Version of the AppSpec file syntax

os: linux  # Operating system where deployment will occur

files:
  - source: /   # Source directory or files to be deployed
    destination: /app  # Destination directory on the target instance
    overwrite: true  # Whether to overwrite existing files

permissions:
  - object: /   # Object (directory or file) to apply permissions to
    pattern: "**"   # Glob pattern to match all files and directories
    owner: ec2-user   # Owner of the files after deployment
    group: ec2-user   # Group of the files after deployment

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh  # Script to run before installation
      timeout: 300  # Timeout for the script (in seconds)
      runas: root  # User to run the script as (root in this case)

  AfterInstall:
    - location: scripts/after_install.sh  # Script to run after installation
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh  # Script to start the application server
      timeout: 300
      runas: root
